config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :users

  resources :clients  do
    collection { post :import }
  end

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  root :to => 'clients#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  ROLES = %w[superadmin admin operator partner agent]
  has_many :clients
  has_many :agents, class_name: 'User',
           foreign_key: 'partner_id'
  has_many :cities, :dependent =>  :destroy

  belongs_to :partner, class_name: 'User'

  validates :login, presence: true
  validates :role, presence: true

  validates_presence_of :password, :on => :create
  validates_confirmation_of :password, :allow_blank => true

  def self.roles
    [['Главный Админ', 'superadmin'], ['Админ', 'admin'], ['Оператор', 'operator'], ['Партнёр', 'partner'], ['Агент', 'agent']]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_role == 'superadmin'
      @users = User.all
    elsif current_role == 'admin'
      @users = User.where(:role => 'operator')
    elsif current_role == 'partner'
      @users = current_user.agents
    else
      @users = User.none
    end

    @users = @users.where(:role => params[:role]) if params[:role].present?
    @users = @users.where(:partner_id => params[:partner_id]) if params[:partner_id].present?
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @cities = @user.cities.all
    @city = @user.cities.build
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if current_role != 'superadmin' && @user.role == 'agent'
      @user.partner = current_user
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:login, :role, :name, :surname, :email, :password, :password_confirmation, :partner_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<script script="text/javascript">
    var selRole = $('.select-role');
    showHidePartner(selRole);
    $(function () {
        selRole.change(function () {
            showHidePartner($(this));
        })
    });

    function showHidePartner(select) {
        if (select.val() == 'agent') {
            $('.field-partner').show();
        } else {
            $('.field-partner').hide();
        }
    }
</script>
<%= form_for(@user, :html => {:class => 'city_form form-client', :style => 'margin:0 auto; width:320px;'}) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <% selection_roles = {}
       if current_role == 'superadmin'
         selection_roles = User.roles
       elsif current_role == 'admin'
         selection_roles = [['Оператор', 'operator']]
       elsif current_role == 'partner'
         selection_roles = [['Агент', 'agent']]
       end
    %>

    <div class="field">
      <%= f.label :login, 'Логин' %>
      <%= f.text_field :login %>
    </div>
    <div class="field">
      <%= f.label :password, 'Пароль' %>
      <%= f.password_field :password %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, 'Подтверждение пароля' %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :email, 'Почта' %>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :role, 'Роль' %>
      <%= f.select :role, options_for_select(selection_roles, @user.role), {}, {:class => 'select-role'} %>
    </div>
    <% if (current_role == 'superadmin') %>
        <div class="field-partner" style="display: none">
          <%= f.label :partner_id %>
          <%= f.select :partner_id, options_from_collection_for_select(User.where(:role => 'partner'), 'id', 'surname', @user.partner_id), :include_blank => true %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :name, 'Фамилия' %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :surname, 'Имя' %>
      <%= f.text_field :surname %>
    </div>
    <div class="actions">
      <%= f.submit 'Сохранить пользователя' %>
    </div>
<% end %>

app/views/users/edit.html.erb
<h1>Редактирование пользователя</h1>

<%= render 'form' %>

<%= link_to 'Показать', @user %> |
<%= link_to 'Назад', users_path %>

app/views/users/index.html.erb
<div class="container">

  <h1>Список пользователей</h1>

  <% if current_role == 'superadmin' %>
      <%= form_tag users_path, :method => 'get', :id => "users_search" do %>
          <p>
            Роль: <%= select_tag :role, options_for_select(User.roles, params[:role]), :prompt => 'Все' %>
            Партнёр: <%= select_tag :partner_id, options_from_collection_for_select(User.where(:role => 'partner'), 'id', 'surname', params[:partner_id]), :prompt => 'Все'  %>
            <%= submit_tag "Поиск", :name => nil %>
          </p>
      <% end %>
  <% end %>
  <%= link_to 'Новый пользователь', new_user_path %>
  <table>
    <thead>
    <tr>
      <th>№</th>
      <th>Логин</th>
      <th>Роль</th>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Партнёр</th>
      <th class="city">Города</th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each_with_index do |user, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= user.login %></td>
          <td><%= user.role %></td>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td>
            <% if user.partner != nil %><%= user.partner.surname + ' ' + user.partner.name %>
            <% end %></td>
          <td class="city">
            <% if user.role == 'partner' || user.role == 'agent' %>
                <%= link_to 'Ред. Города', user %><br/>
                <% user.cities.each do |city| %>
                    <%= city.city %>
                <% end %>
            <% end %>
          </td>
          <td><%= link_to image_tag('edit-icon.png'), edit_user_path(user) %></td>
          <td><%= link_to image_tag('delete-icon.png'), user, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>
</div>

app/views/users/new.html.erb
<h1>Новый пользователь</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Логин:</strong>
  <%= @user.login %>
</p>

<p>
  <strong>Роль:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Фамилия:</strong>
  <%= @user.surname %>
</p>
<p>
  <strong>Имя:</strong>
  <%= @user.name %>
</p>


<%= link_to 'Редактировать', edit_user_path(@user) %> |
<%= link_to 'Назад', users_path %>

<% if @user.role =='partner' || @user.role == 'agent' %>
    <%= render 'cities/form' %>
    <h3>Города <%= @user.login %></h3>
    <table>
      <% if @cities.count > 0 %>
          <th>№</th>
          <th>Регион</th>
          <th>Город</th>
          <th>Код Кладра</th>
          <th>Удаление</th>
      <% end %>

      <% @cities.sort_by { |city| [city.region, city.city] }.each_with_index do |city, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= city.region %></td>
            <td><%= city.city %></td>
            <td><%= city.city_code %></td>
            <td><%= link_to 'Удалить', city_path(city), method: :delete, data: {confirm: 'Вы уверены?'} %></td>
          </tr>
      <% end %>
    </table>
<% end %>