config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :users

  resources :clients  do
    collection { post :import }
  end

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  root :to => 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :surname, presence: true
  validates :phone, :format => {:with => /\A(\+1)?[0-9]{10}\z/, :message => "Неверный номер телефона"}
  validates :snils, snils: true

  scope :operator_status, -> (operator_status) { where operator_status: operator_status }
  scope :partner_status, -> (partner_status) { where partner_status: partner_status }

  def self.sel_stage
    [['Этап 1', '1'], ['Этап 2', '2']]
  end

  def self.sel_op_status
    ['', 'Недозвон-1', 'Недозвон-2', 'Недозвон-Итог', 'Оформлен', 'Отказ', 'Выключен', 'Перезвон', 'Дубль']
  end

  def self.sel_ag_status
    ['', 'Недозвон-1', 'Недозвон-2', 'Недозвон-Итог', 'Договор', 'Встреча', 'Перенос', 'Отказ-телефон', 'Отказ-встреча', 'Выключен', 'Неверный номер', 'Дубль']
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    if (file != nil)
      ##Загрузка примера
      spreadsheet1 = open_spreadsheet(file)
      header = spreadsheet1.row(2)
      (3..spreadsheet1.last_row).each do |i|
        row = spreadsheet1.row(i)
        client = Client.new()
        client.statement_date = row[header.index('Дата')]
        if client.statement_date == nil
          break
        end
        region = row[header.index('Область')].strip
        region = region.split(' ')[1..-1].join(' ') if region.start_with?('г.', 'обл.', 'респ.', 'край.', 'Аобл.', 'АО.') ## первое слово убираем
        client.region = region

        city = row[header.index('Город')].strip
        city = city.split(' ').drop(1).join(' ') if city.start_with?('г.', 'п.', 'с.') ## первое слово убираем
        client.city = city

        fio = row[header.index('ФИО')].split()
        client.surname = fio[0].mb_chars.downcase.capitalize.to_s
        client.name = fio[1].mb_chars.downcase.capitalize.to_s
        client.patronymic = fio[2].mb_chars.downcase.capitalize.to_s
        client.snils = row[header.index('СНИЛС')].gsub(/[^0-9A-Za-z]/, '')
        client.address = row[header.index('Адрес')]
        client.birth_date = row[header.index('Дата рождения')]
        client.phone = row[header.index('Телефон')].split()[0].gsub(/[^0-9]/, '')
        client.operator_status = row[header.index('Статус')]
        client.operator_comment = row[header.index('Комментарий')]
        client.stage = '1' ###Этап 1 всегда

        #row = Hash[[header, spreadsheet1.row(i)].transpose]
        #client = find_by_id(row["id"]) || new
        #client.attributes = row.to_hash
        client.save!
      end
    end
  end

  def self.open_spreadsheet(file)

    case File.extname(file.original_filename)
      when ".csv" then
        Roo::Excel.new(file.path, file_warning: :ignore)
      when ".xls" then
        Roo::Excel.new(file.path, file_warning: :ignore)
      when ".xlsx" then
        Roo::Excelx.new(file.path, file_warning: :ignore)
      else
        raise "Неизвестный тип файла: #{file.original_filename}"
    end
  end

  def self.search(search)
    if search
      where('name LIKE ? OR surname LIKE ? OR phone LIKE ? OR snils LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search.gsub(/[^0-9]/, '')}%")
    else
      where(nil)
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  # выбираем клиентов для разных типов ролей
  def index
    @clients = [];
    if current_role == 'superadmin' or current_role == 'admin'
      @clients = Client.all
    elsif current_role == 'operator'
      @clients = current_user.clients
    elsif current_role == 'partner'
      cur_city_codes = []
      current_user.cities.each do |city|
        cur_city_codes.push(city.city_code)
      end
      @clients = Client.where(:city_code => cur_city_codes)
    elsif current_role == 'agent'
      cur_city_codes = []
      current_user.partner.cities.each do |city|
        if (current_user.cities.map { |c| c.city_code }.include? city.city_code)
          cur_city_codes.push(city.city_code)
        end
      end
      @clients = Client.where(:city_code => cur_city_codes)
    else
      @clients = Client.none
    end

    @clients = @clients.search(params[:search])
    @clients = @clients.operator_status(params[:operator_status]) if params[:operator_status].present?
    @clients = @clients.partner_status(params[:partner_status]) if params[:partner_status].present?
    @clients = @clients.where('birth_date >= ?', params[:birth_date_from].to_date.to_formatted_s(:db)) if params[:birth_date_from].present?
    @clients = @clients.where('birth_date <= ?', params[:birth_date_to].to_date.to_formatted_s(:db)) if params[:birth_date_to].present?
    @clients = @clients.where('city_code LIKE ?', "#{params[:region_code][0..1]}%" ) if (params[:region_code].present? && !params[:city_code].present?)
    @clients = @clients.where('city_code = ?', "#{params[:city_code]}" ) if params[:city_code].present?
    @clients = @clients.order(sort_column + ' ' + sort_direction).page(params[:page]).per(params[:per_page])

    respond_to do |format|
      format.html
      format.js
      format.xls # { send_data @clients.to_csv(col_sep: "\t") }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.statement_date = Time.now
    format_snils
    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Клиент успешно создан' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      format_snils
      if (@client.stage == 1 && params[:client][:stage] == '2')
        params[:client][:statement_date] = Time.now
      end

      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: 'Клиент успешно обновлён' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Клиент успешно удалён' }
      format.json { head :no_content }
    end
  end

  def import
    Client.import(params[:file])
    redirect_to clients_url, notice: "Импорт клиентов успешно завершён."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_client
    @client = Client.find(params[:id])
  end

  def format_snils
    params[:client][:snils] = params[:client][:snils].gsub(/[^0-9A-Za-z]/, '')
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def client_params
    params.require(:client).permit(:name, :surname, :patronymic, :birth_date, :phone, :stage, :meeting_date, :operator_status, :operator_comment, :partner_status, :partner_comment, :user_id, :statement_date, :city, :region, :city_code, :snils, :address, :status_date, :transfer_date, :passport_number, :passport_issued, :passport_date, :birth_place, :sex)
  end

  def sort_column
    Client.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_clients.html.erb
<script type="text/javascript">
    /////AJAX для формы клиентов
    $(function () {
        $("#clients th, #clients .pagination").on("click", 'a', function () {
            $.getScript(this.href);
            return false;
        });
        $("#clients_search").submit(function () {
            $.get(this.action, $(this).serialize(), null, "script");
            return false;
        });
    });
</script>

<% if current_role == 'superadmin' || current_role == 'admin' %>
    <div class="excel_block">
      <span class="dl-excel">Скачать Excel:
        <%= link_to image_tag("excel.gif"), clients_path(format: "xls", :params => params) %>   </span>

      <%= form_tag import_clients_path, multipart: true, :class => 'upload_form' do %>
          Импорт клиентов:
          <%= file_field_tag :file %>
          <%= submit_tag "Импорт клиентов" %>
      <% end %>
    </div>
<% end %>

<div style="height:24px"><%= paginate @clients %>
</div>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table>
  <thead>
  <tr>
    <th>№</th>
    <th><%= sortable 'statement_date', 'Дата заявки' %></th>
    <th><%= sortable 'surname', 'ФИО' %></th>
    <th><%= sortable 'birth_date', 'Дата рождения' %></th>
    <th>Телефон</th>
    <th>Регион</th>
    <th>Город</th>
    <th>Этап</th>
    <th>Статус оператора</th>
    <th>Статус партнёра</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @clients.each_with_index do |client, index| %>
      <tr class="city_code_<%= client.city_code %>">
        <td><%= index + 1 %></td>
        <td><%= client.statement_date %></td>
        <td><%= client.surname + ' ' + client.name + ' ' + client.patronymic %>
          <br/><span class="snils"><%= (client.snils.present? ? Snils.new(client.snils).formatted : '') %></span></td>
        <td><%= client.birth_date %></td>
        <td>+7 <%= client.phone %></td>

        <td class="r"><%= client.region %></td>
        <td class="c"><%= client.city %></td>
        <td>Этап <%= client.stage %></td>
        <td class='call-<%= client.operator_status %>'><%= client.operator_status %>
          <br><span class="comment"><%= client.operator_comment %></span></td>
        <td><%= client.partner_status %><br/><span class="comment"><%= client.partner_comment %></span></td>

        <% if can? :update, client %>
            <td><%= link_to image_tag('edit-icon.png'), edit_client_path(client) %>   </td>
        <% end %>
        <% if can? :destroy, client %>
            <td><%= link_to image_tag('delete-icon.png'), client, method: :delete, data: {confirm: 'Are you sure?'} %>   </td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/clients/_form.html.erb
<script script="text/javascript">
    $(function () {
        fillInCityKLADR();
        $('#client_meeting_date').add('#client_status_date').add('#client_transfer_date').datepicker({
            dateFormat: "dd/mm/yy",
            numberOfMonths: 3,
            showButtonPanel: true
        });
        $('#client_birth_date').datepicker({
            dateFormat: "dd/mm/yy",
            yearRange: "1957:2002",
            changeMonth: true,
            changeYear: true
        });

        $('#client_passport_date').datepicker({
            dateFormat: "dd/mm/yy",
            yearRange: "-30:+0",
            changeMonth: true,
            changeYear: true
        });

        $("form").on("keypress", function (e) {
            if (e.keyCode == 13) {
                return false;
            }
        });

        if ($('input.city_code').val() == '' && $('input.city').val() != '') {
            $('input.region').focusin();
            $('input.region').blur();
            $('input.city').focusin();
            $('input.city').blur();
        }

        //Проверяем сити-код при загрузке городов
        $('input.region').kladr({
            token: 'token',
            key: 'key',
            type: $.kladr.type.region,
            check: function (obj) {
                if (obj) {
                    $('input.region').css('color', 'black');
                } else {
                    $('input.region').css('color', 'red');
                }
            }
        });
        //Проверка города
        $('input.city').kladr({
            token: 'token',
            key: 'key',
            type: $.kladr.type.city,
            check: function (obj) {
                if (obj) {
                    $('input.city').css('color', 'black');
                    $('input.city_code').val(obj.id);
                } else {
                    $('input.city').css('color', 'red');
                }
            }
        });

        //Запрещаем исправлять
        <% if ['operator', 'admin'].include? current_role %>
        $('#client_partner_status').prop('disabled', true);
        $('#client_partner_comment').prop('disabled', true);
        $('#client_meeting_date').prop('disabled', true);
        $('#client_status_date').prop('disabled', true);
        $('#client_transfer_date').prop('disabled', true);
        <%end%>


        <% if ['agent', 'partner'].include? current_role %>
        $('#client_surname').prop('disabled', true);
        $('#client_name').prop('disabled', true);
        $('#client_patronymic').prop('disabled', true);
        $('#client_birth_date').prop('disabled', true);
        $('#client_phone').prop('disabled', true);
        $('#client_region').prop('disabled', true);
        $('#client_city').prop('disabled', true);
        $('#client_address').prop('disabled', true);
        $('#client_snils').prop('disabled', true);
        $('#client_operator_status').prop('disabled', true);
        $('#client_operator_comment').prop('disabled', true);
        $('#clien_sex').prop('disabled', true);
        $('#clien_passport_number').prop('disabled', true);
        $('#clien_passport_issued').prop('disabled', true);
        $('#clien_passport_date').prop('disabled', true);
        <%end%>

        <% if ['agent', 'partner', 'operator'].include? current_role %>
        $('#client_stage').prop('disabled', true);
        $('#client_user_id').prop('disabled', true);
        <%end%>

        $('form input').add('form select').add('form textarea').each(function () {
            if ($(this).prop('disabled') == true) {
                $(this).siblings('label').css('font-weight', 'normal');
            }
        });
    });
</script>

<%= form_for(@client, :html => {:class => 'form-client city_form', :style => 'margin: 0 auto; width: 800px;'}) do |f| %>
    <% if @client.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

          <ul>
            <% @client.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="clearfix">
      <div class="left">
        <div class="js-form-address">
          <div class="field">
            <%= f.label :region, 'Регион' %>
            <%= f.text_field :region, :class => 'region' %>
          </div>
          <div class="field">
            <%= f.label :city, 'Город' %>
            <%= f.text_field :city, :class => 'city' %>
            <%= f.hidden_field :city_code, :class => 'city_code' %>
          </div>
          <div class="tooltip" style="display: none;"><b></b><span></span></div>
        </div>

        <div class="field">
          <%= f.label :surname, 'Фамилия' %>
          <%= f.text_field :surname %>
        </div>
        <div class="field">
          <%= f.label :name, 'Имя' %>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :patronymic, 'Отчество' %>
          <%= f.text_field :patronymic %>
        </div>


        <div class="field">
          <%= f.label :snils, 'СНИЛС' %>
          <%= f.text_field :snils, :value => @client.snils.present? ? Snils.new(@client.snils).formatted : '' %>
        </div>

        <div class="field">
          <%= f.label :sex, 'Пол' %>
          <%= f.select :sex, options_for_select([['Пол', ''], ['Мужской', 'M'], ['Женский', 'F']], @client.sex) %>
        </div>

        <div class="field">
          <%= f.label :passport_number, 'Номер паспорта' %>
          <%= f.text_field :passport_number, :maxlength => '14' %>
        </div>

        <div class="field">
          <%= f.label :passport_issued, 'Кем выдан паспорт' %>
          <%= f.text_area :passport_issued %>
        </div>

        <div class="field">
          <%= f.label :passport_date, 'Дата выдачи паспорта' %>
          <%= f.text_field :passport_date %>
        </div>

        <div class="field">
          <%= f.label :birth_place, 'Место рождения' %>
          <%= f.text_area :birth_place %>
        </div>

        <div class="field">
          <%= f.label :birth_date, 'Дата рождения' %>
          <%= f.text_field :birth_date %>
        </div>
        <div class="field">
          <%= f.label :phone, 'Телефон' %>
          +7 <%= f.text_field :phone, :style => 'width:142px', :maxlength => '10' %>
        </div>
        <div class="field">
          <%= f.label :address, 'Адрес' %>
          <%= f.text_area :address %>
        </div>
      </div>
      <div class="right">


        <div class="field">
          <%= f.label :user_id, 'Оператор' %>
          <%= collection_select(:client, :user_id, User.where(:role => 'operator'), :id, :login, :prompt => 'Please select operator') %>
        </div>

        <div class="field">
          <%= f.label :stage, 'Этап' %>
          <%= f.select :stage, options_for_select(Client.sel_stage, @client.stage), {}, {:class => 'select-stage'} %>
        </div>
        <div class="field">
          <%= f.label :operator_status, 'Статус оператора' %>
          <%= f.select :operator_status, options_for_select(Client.sel_op_status, @client.operator_status), {}, {:class => 'select-op-status'} %>
        </div>
        <div class="field">
          <%= f.label :operator_comment, 'Комментарий оператора' %>
          <%= f.text_area :operator_comment %>
        </div>

        <div class="field">
          <%= f.label :status_date, 'Дата статуса' %>
          <%= f.text_field :status_date %>
        </div>

        <div class="field">
          <%= f.label :partner_status, 'Статус партнёра' %>
          <%= f.select :partner_status, options_for_select(Client.sel_ag_status, @client.partner_status), {}, {:class => 'select-op-status'} %>
        </div>

        <div class="field">
          <%= f.label :transfer_date, 'Дата переноса/перезвона' %>
          <%= f.text_field :transfer_date %>
        </div>

        <div class="field">
          <%= f.label :partner_comment, 'Комментарий партнёра' %>
          <%= f.text_area :partner_comment %>
        </div>
        <div class="field">
          <%= f.label :meeting_date, 'Плановая дата встречи' %>
          <%= f.text_field :meeting_date %>
        </div>

      </div>


    </div>
    <div class="actions">
      <%= f.submit 'Сохранить Клиента' %>
    </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Редактирование клиента</h1>

<%= render 'form' %>

<%= link_to 'Показать', @client %> |
<%= link_to 'Назад', clients_path %>

app/views/clients/index.html.erb
<script type="text/javascript">
    //Отправляешь форму при смене количества записей на страницу
    $(function () {
        fillInCityKLADR();
        $('#per_page').change(
                function () {
                    $('#clients_search').submit();
                });

        $('select#operator_status option').first().text('Статус оператора');
        $('select#partner_status option').first().text('Статус партнёра');

        $('#birth_date_from').add('#birth_date_to').datepicker({
            dateFormat: "dd/mm/yy",
            yearRange: "1957:2002",
            changeMonth: true,
            changeYear: true
        });
    });
</script>

<div class="clients-container">
  <h1>Список клиентов</h1>

  <div class="color-tips">Подсказки: <span class="color-kladr">город не подтверждён КЛАДР</span>
    <span class="color-refuse-call">отказ</span></div>



  <% if can? :create, Client.first %>
      <span style="display: inline-block; position: absolute; top:0px; left:0px; font-weight: bold"><%= link_to 'Добавить нового клиента', new_client_path %> </span>
  <% end %>

  <%= form_tag clients_path, :method => 'get', :id => "clients_search", :class => 'city_form' do %>
      <p>
        <%= text_field_tag :search, params[:search], :placeholder => 'фамилия, имя, СНИЛС, тел.' %>
        <%= select_tag :operator_status, options_for_select(Client.sel_op_status, params[:operator_status]) %>
        <%= select_tag :partner_status, options_for_select(Client.sel_ag_status, params[:partner_status]) %>
        <%= text_field_tag :birth_date_from, params[:birth_date_from], :placeholder => 'дата рожд. от' %>
        <%= text_field_tag :birth_date_to, params[:birth_date_to], :placeholder => 'дата рожд. до' %>
        <span class="js-form-address"><%= text_field_tag :region, params[:region], :class => 'region', :placeholder => 'регион' %>
          <%= text_field_tag :city, params[:city], :class => 'city', :placeholder => 'город' %>
          <%= hidden_field_tag :region_code, params[:region_code], :class => 'region_code' %>
          <%= hidden_field_tag :city_code, params[:city_code], :class => 'city_code' %> </span>
        <%= submit_tag "Поиск", :name => nil %>
      </p>


      <span style="position: absolute; right:0px; top:40px">Выводить по <%= select_tag :per_page, options_for_select([25, 50, 100, 500, 1000, 5000], params[:per_page]) %></span>
  <% end %>
  <div id="clients"><%= render 'clients' %></div>

</div>

app/views/clients/index.js.erb
$("#clients").html("<%= escape_javascript(render('clients')) %>");

app/views/clients/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">N</Data></Cell>
        <Cell><Data ss:Type="String">ФИО</Data></Cell>
        <Cell><Data ss:Type="String">Дата заявки</Data></Cell>
        <Cell><Data ss:Type="String">Дата рождения</Data></Cell>
        <Cell><Data ss:Type="String">СНИЛС</Data></Cell>
        <Cell><Data ss:Type="String">Телефон</Data></Cell>
        <Cell><Data ss:Type="String">Регион</Data></Cell>
        <Cell><Data ss:Type="String">Город</Data></Cell>
        <Cell><Data ss:Type="String">Адрес</Data></Cell>
        <Cell><Data ss:Type="String">Ответственный оператор</Data></Cell>
        <Cell><Data ss:Type="String">Этап обработки</Data></Cell>
        <Cell><Data ss:Type="String">Статус оператора</Data></Cell>
        <Cell><Data ss:Type="String">Комментарий оператора</Data></Cell>
        <Cell><Data ss:Type="String">Статус партнёра</Data></Cell>
        <Cell><Data ss:Type="String">Комментарий партнёра</Data></Cell>
        <Cell><Data ss:Type="String">Плановая дата встречи</Data></Cell>
      </Row>
      <% @clients.each do |client| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= client.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.surname + ' ' + client.name + ' ' + client.patronymic %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.statement_date.to_s %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.birth_date.to_s %></Data></Cell>
            <Cell><Data ss:Type="String"><%= Snils.new(client.snils).formatted %></Data></Cell>
            <Cell><Data ss:Type="String">+7<%= client.phone %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.region %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.city %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.address %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.user.login if !client.user.nil? %></Data></Cell>
            <Cell><Data ss:Type="String">Этап <%= client.stage %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.operator_status %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.operator_comment %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.partner_status %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.partner_comment %></Data></Cell>
            <Cell><Data ss:Type="String"><%= client.meeting_date.to_s %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/clients/new.html.erb
<h1>Новый клиент</h1>

<%= render 'form' %>

<%= link_to 'Назад', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @client.surname %>
</p>

<p>
  <strong>Patronymic:</strong>
  <%= @client.patronymic %>
</p>

<p>
  <strong>Birth Date:</strong>
  <%= @client.birth_date %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<%= link_to 'Редактировать', edit_client_path(@client) %> |
<%= link_to 'Назад', clients_path %>