config/routes.rb
Rails.application.routes.draw do
  resources :cities

  resources :users

  resources :clients  do
    collection { post :import }
  end

  resources :user_sessions, only: [:create, :destroy]
  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  root :to => 'clients#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  belongs_to :user
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  load_and_authorize_resource
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city.user, notice: 'Город ' + @city.city + ' был успешно добавлен' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city.user, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @user = @city.user
    @city.destroy
    respond_to do |format|
      format.html { redirect_to @user, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:region, :city, :city_code, :user_id)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<script script="text/javascript">
    $(function () {
        fillInCityKLADR();
    });
</script>

<%= form_for(@city, :html => {:class => 'city_form'}) do |f| %>
    <h3>Добавить город</h3>
    <% if @city.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

          <ul>
            <% @city.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="js-form-address">
      <div class="field">
        <%= f.label :region %><br>
        <%= f.text_field :region, :class => 'region' %>
      </div>
      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city, :class => 'city' %>
        <%= f.hidden_field :city_code, :class => 'city_code' %>
      </div>
      <div class="tooltip" style="display: none;"><b></b><span></span></div>
    </div>
    <%= f.hidden_field :user_id %>
    <div class="actions">
      <%= f.submit 'Добавить город' %>
    </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Показать', @city %> |
<%= link_to 'Назад', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Region</th>
      <th>Name</th>
      <th>Code</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.region %></td>
        <td><%= city.city %></td>
        <td><%= city.city_code %></td>
        <td><%= city.user_id %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Region:</strong>
  <%= @city.region %>
</p>

<p>
  <strong>Name:</strong>
  <%= @city.city %>
</p>

<p>
  <strong>Code:</strong>
  <%= @city.city_code %>
</p>

<p>
  <strong>User:</strong>
  <%= @city.user_id %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>